import random
import string

email = ""
senha = ""

numeros = [1, 2, 3]
print(random.choice(numeros))

if numeros == 1:
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_letters)
    email += random.choice(string.ascii_uppercase)
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)

    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
elif numeros == 2:
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_letters)
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)
    email += random.choice(string.ascii_uppercase)
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)

    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_letters)
else:
    email += random.choice(string.ascii_uppercase)
    email += random.choice(string.ascii_uppercase)
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email += random.choice(string.ascii_uppercase)
    email  += random.choice(string.ascii_letters)
    email  += random.choice(string.punctuation)
    email  += random.choice(string.ascii_lowercase)
    email  += random.choice(string.digits)

    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_uppercase)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.punctuation)
    senha += random.choice(string.ascii_lowercase)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.ascii_letters)
    senha += random.choice(string.digits)
    senha += random.choice(string.ascii_uppercase)

print(email + "@gmail.com")
print(senha)


